%Returns a trained Residual ARCNN model

function [net] = train_model()
tic
doTraining = true; 
dsTrain = prep_train_data();
layers = ARCNN_model();

maxEpochs = 10;
initLearningRate = 0.1; %0.001 , 0,01
l2reg = 0.0001;% 0.0001;
batchSize = 64;

options = trainingOptions('sgdm', ...
    'Momentum',0.9, ...
    'InitialLearnRate',initLearningRate, ...
    'LearnRateSchedule','piecewise', ...
    'GradientThresholdMethod','absolute-value', ...
    'GradientThreshold',0.005, ...
    'L2Regularization',l2reg, ...
    'MiniBatchSize',batchSize, ...
    'MaxEpochs',maxEpochs, ...
    'Plots','training-progress', ...
    'Verbose',false);

% options2 = trainingOptions("adam", ...
%     'MaxEpochs',50, ...
%     'MiniBatchSize',batchSize, ...
%     'Plots',"training-progress", ...
%     'Verbose',false);

if doTraining  
    modelDateTime = string(datetime('now','Format',"yyyy-MM-dd-HH-mm-ss"));
    [net,info] = trainNetwork(ARCNN_prep_data(),layers,options);
    save(strcat("trainedJPEG",type,"model",modelDateTime,"-Epoch-",num2str(maxEpochs),".mat"),'net');
end

toc